#!/usr/bin/env python
"""
refstore.py -- the reference set as ONE folder, not a campaign.

WHAT THIS IS
    The reference set is a global asset: a list of known Materials Project
    phases, each recomputed with OUR DFT settings, used to build convex hulls
    for any campaign.  It is NOT a campaign.  It has no generation, no
    screening, no calibration -- just two VASP runs per structure.

    Before this script it was spread over three places (an MP cache, a `final/`
    tree, and a live campaign workdir whose folders were named `dft-110-relax`),
    and results only reached `final/` when someone ran a separate collect step.
    This script replaces all of that with one folder and one CSV.

LAYOUT (everything lives under $CSPFLOW_STORE, default /projects/mmi/cspflow-shared/store)

    settings.yaml            the ONE DFT policy.  Never overridden per-run.
    machine.yaml             the ONE machine profile (partitions, POTCAR paths).
    index.csv                THE bookkeeping file.  Regenerated by `index`.
    index.json               same content, for scripts.
    mp-cache/                MP downloads (json), shared across campaigns.
    jobs/                    task lists + slurm logs.
    structures/
        mp-13-Fe/            <-- MP id AND composition, so the tree is greppable
            info.json        what this phase is + where it came from
            mlip/            MatterSim relax (GPU job)     CONTCAR relaxed.cif mlip.json
            dft_relax/       VASP relax   \  ONE CPU job: relax -> CONTCAR becomes
            dft_static/      VASP static  /  static POSCAR -> static

WHY THE COMPOSITION IS IN THE FOLDER NAME
    So `ls structures | grep Ce` answers "what Ce phases do I have" without
    opening a database.

THE ONE RULE THAT CANNOT BE RELAXED
    Every energy on one hull must come from the same DFT policy.  Mixing
    policies shifted our energies by +0.19 eV/atom against MP, while the
    selection threshold is 0.06 eV/atom.  So settings.yaml is read from the
    store root and nothing overrides it.  You never type a recipe id.

INPUTS
    $CSPFLOW_STORE/settings.yaml, machine.yaml   (policy, required)
    $MP_API_KEY                                  (only for `add`, never written down)
    Materials Project                            (only for `add`, then cached)

OUTPUTS
    $CSPFLOW_STORE/structures/<mp-id>-<formula>/...
    $CSPFLOW_STORE/index.csv, index.json
    $CSPFLOW_STORE/jobs/<name>.tasks             one folder path per line

COMMANDS
    refstore.py migrate  [--apply]            fold old layouts into structures/
    refstore.py add      CHEMSYS... [--apply] fetch MP, add what is missing
    refstore.py inputs   DIR --stage relax|static     write VASP input files
    refstore.py index                         rescan the tree -> index.csv
    refstore.py status   [CHEMSYS]            human summary
    refstore.py submit   mlip|dft [--limit N] [--apply]   task list + sbatch
    refstore.py hull     CHEMSYS              build the hull from index.csv

RUN
    export CSPFLOW_STORE=/projects/mmi/cspflow-shared/store
    python scripts/refstore.py status
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import shutil
import subprocess
import sys
import time
from collections import Counter
from pathlib import Path

from cspflow.dft.vasp.parse import tail_text

DEFAULT_STORE = Path("/projects/mmi/cspflow-shared/store")

# Phases further above MP's own hull than this cannot change our hull, so we do
# not spend DFT on them.  One number, used everywhere.
DEFAULT_CUT = 0.5          # eV/atom

STAGES = ("relax", "static")
STAGE_DIR = {"relax": "dft_relax", "static": "dft_static"}


# --------------------------------------------------------------------------
# The store
# --------------------------------------------------------------------------

def store_root() -> Path:
    return Path(os.environ.get("CSPFLOW_STORE") or DEFAULT_STORE)


def structures_dir() -> Path:
    return store_root() / "structures"


def slug(mp_id: str, formula: str) -> str:
    """`mp-13` + `Fe` -> `mp-13-Fe`.  Reduced formulas are already path-safe."""
    return f"{mp_id}-{re.sub(r'[^A-Za-z0-9]', '', formula)}"


def mp_id_of(folder: Path) -> str:
    return folder.name.split("-", 2)[0] + "-" + folder.name.split("-", 2)[1]


def policy():
    """The ONE DFT policy, plus the machine.  Both from the store root."""
    import yaml

    from cspflow.cli import _dft_and_recipe
    from cspflow.config.schema import Machine

    root = store_root()
    settings = root / "settings.yaml"
    if not settings.is_file():
        sys.exit(f"no {settings}. The store needs exactly one DFT policy file.")
    dft, recipe, _ = _dft_and_recipe(settings, None)

    mfile = root / "machine.yaml"
    if not mfile.is_file():
        sys.exit(f"no {mfile}. The store needs exactly one machine profile.")
    machine = Machine(**yaml.safe_load(mfile.read_text()))
    return dft, recipe, machine


def read_atoms(path: Path):
    from ase.io import read
    return read(str(path))


def reduced_formula(atoms) -> str:
    from pymatgen.core import Composition
    return Composition(atoms.get_chemical_formula()).reduced_formula


def chemsys_of(atoms) -> str:
    return "-".join(sorted(set(atoms.get_chemical_symbols())))


# --------------------------------------------------------------------------
# migrate -- fold the old layouts into structures/
# --------------------------------------------------------------------------

OLD_SUBDIRS = {"relax": "dft_relax", "static": "dft_static", "mlip": "mlip",
               "dft_relax": "dft_relax", "dft_static": "dft_static"}
RUN_DIR = re.compile(r"^dft-(\d+)-(.+)$")


def _atoms_for(folder: Path):
    """Composition of an existing structure folder, from whatever it has."""
    for rel in ("relax/POSCAR", "dft_relax/POSCAR", "static/POSCAR",
                "mlip/CONTCAR", "relax/CONTCAR", "POSCAR.orig", "POSCAR"):
        p = folder / rel
        if p.is_file() and p.stat().st_size > 0:
            try:
                return read_atoms(p)
            except Exception:
                continue
    return None


def cmd_migrate(a) -> None:
    root = store_root()
    dest_root = structures_dir()
    moves: list[tuple[Path, Path]] = []
    problems: list[str] = []
    stats: Counter = Counter()

    # ---- source 1: the old `final/` tree, `final/mp-13/{relax,static,mlip}`
    final = root / "final"
    if final.is_dir():                       # the pre-reorganisation layout
        for d in sorted(final.iterdir()):
            if not d.is_dir() or not d.name.startswith("mp-"):
                continue
            atoms = _atoms_for(d)
            if atoms is None:
                stats["no_structure"] += 1
                problems.append(f"{d.name}: no readable POSCAR/CONTCAR anywhere")
                continue
            target = dest_root / slug(d.name, reduced_formula(atoms))
            for child in sorted(d.iterdir()):
                new = OLD_SUBDIRS.get(child.name, child.name)
                moves.append((child, target / new))
            stats["from_final"] += 1

    # ---- source 2: any campaign workdir, `<camp>/dft/dft-<row>-<stage>`
    # `archive/` is where migrated husks are parked; re-reading it would try to
    # migrate the same run directories a second time.
    for camp in sorted(root.iterdir()):
        if camp.name in ("archive", "structures", "mp-cache", "jobs", "logs"):
            continue
        dft = camp / "dft"
        db = camp / "campaign.db"
        if not (camp.is_dir() and dft.is_dir() and db.is_file()):
            continue
        from cspflow.db.store import Store
        with Store.open(db) as store:
            by_row = {int(r.id): str(r.key_value_pairs.get("mp_id") or "")
                      for r in store.structures()}
        for d in sorted(dft.iterdir()):
            if not d.is_dir():
                continue
            m = RUN_DIR.match(d.name)
            if not m:
                continue
            row, stage = int(m.group(1)), m.group(2)
            mp_id = by_row.get(row)
            if not mp_id:
                stats["no_mp_id"] += 1
                problems.append(f"{camp.name}/{d.name}: row {row} has no mp_id")
                continue
            atoms = _atoms_for(d)
            if atoms is None:
                stats["no_structure"] += 1
                problems.append(f"{camp.name}/{d.name}: no readable POSCAR")
                continue
            target = dest_root / slug(mp_id, reduced_formula(atoms))
            moves.append((d, target / STAGE_DIR.get(stage, stage)))
            stats[f"from_{camp.name}"] += 1

    print(f"store        {root}")
    print(f"destination  {dest_root}")
    for k, v in sorted(stats.items()):
        print(f"{k:<24} {v}")
    print(f"{'moves':<24} {len(moves)}")

    collisions = [(s, t) for s, t in moves if t.exists()]
    if collisions:
        print(f"{'already at destination':<24} {len(collisions)} (skipped)")
    for p in problems[:20]:
        print("  problem:", p)
    if len(problems) > 20:
        print(f"  ... and {len(problems) - 20} more")

    if not a.apply:
        print("\ndry run. add --apply to move.")
        return

    done = 0
    for src, tgt in moves:
        if tgt.exists() or not src.exists():
            continue
        tgt.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(tgt))
        done += 1
    print(f"moved {done}")

    # Remove the husks the moves left behind, but only if truly empty.
    for parent in {s.parent for s, _ in moves}:
        try:
            if parent.is_dir() and not any(parent.iterdir()):
                parent.rmdir()
        except OSError:
            pass


# --------------------------------------------------------------------------
# index -- rescan the tree, write index.csv.  Derived, so it cannot drift.
# --------------------------------------------------------------------------

COLUMNS = [
    "mp_id", "formula", "chemsys", "n_atoms", "folder",
    "mlip_state", "e_mlip_relaxed",
    "relax_state", "relax_converged", "relax_core_hours",
    "static_state", "e_static_eV", "e_per_atom_eV", "magnetization_uB",
    "ready", "fail_reason",
]


def scan_one(folder: Path) -> dict:
    from cspflow.dft.vasp.parse import read_job_directory

    row = {c: "" for c in COLUMNS}
    row["folder"] = folder.name
    parts = folder.name.split("-")
    row["mp_id"] = "-".join(parts[:2])
    row["formula"] = "-".join(parts[2:])

    info = folder / "info.json"
    if info.is_file():
        try:
            d = json.loads(info.read_text())
            row["chemsys"] = d.get("chemsys", "")
            row["formula"] = d.get("formula", row["formula"])
        except Exception:
            pass

    mlip = folder / "mlip" / "mlip.json"
    if mlip.is_file():
        try:
            d = json.loads(mlip.read_text())
            row["mlip_state"] = "done" if d.get("converged", True) else "unconverged"
            row["e_mlip_relaxed"] = d.get("e_mlip_relaxed", d.get("energy", ""))
        except Exception:
            row["mlip_state"] = "unreadable"
    elif (folder / "mlip").is_dir():
        row["mlip_state"] = "partial"
    else:
        row["mlip_state"] = "todo"

    fails = []
    for stage in STAGES:
        d = folder / STAGE_DIR[stage]
        if not d.is_dir():
            row[f"{stage}_state"] = "todo"
            continue
        if not (d / "OUTCAR").is_file() and not (d / "INCAR").is_file():
            row[f"{stage}_state"] = "todo"
            continue
        out = read_job_directory(d)
        row[f"{stage}_state"] = out.state
        if out.exit_reason:
            fails.append(f"{stage}: {out.exit_reason}")
        if stage == "relax":
            row["relax_converged"] = out.converged
            row["relax_core_hours"] = round(out.core_hours, 2)
            if not row["chemsys"] and out.potcar_symbols:
                row["chemsys"] = "-".join(sorted({s.split("_")[0]
                                                  for s in out.potcar_symbols}))
        else:
            row["n_atoms"] = out.n_atoms or ""
            row["e_static_eV"] = out.energy if out.energy is not None else ""
            row["e_per_atom_eV"] = (round(out.e_per_atom, 6)
                                    if out.e_per_atom is not None else "")
            row["magnetization_uB"] = (out.magnetisation
                                       if out.magnetisation is not None else "")

    # A folder that has not been run yet has no OUTCAR and no POTCAR to read the
    # chemistry from, so fall back to whatever geometry it does have.  Without
    # this, `status Ce-Fe-B` silently omits everything still to do.
    if not row["chemsys"] or not row["n_atoms"]:
        atoms = _atoms_for(folder)
        if atoms is not None:
            row["chemsys"] = row["chemsys"] or chemsys_of(atoms)
            row["n_atoms"] = row["n_atoms"] or len(atoms)
            if not row["formula"] or row["formula"] == "-".join(parts[2:]):
                row["formula"] = reduced_formula(atoms)

    # Backfilling n_atoms above is not enough on its own: e_per_atom was derived
    # EARLIER, from the OUTCAR's own n_atoms, and a row that needed the backfill
    # therefore carries a total energy with no per-atom energy. It then looks
    # complete -- static_state done, ready True -- while being invisible to any
    # hull built on e_per_atom_eV. Derive it here, once n_atoms is known.
    # (2026-09-15: 65 rows were in this state, including mp-4459 Ce2Fe14B.)
    if (not row["e_per_atom_eV"]) and row["e_static_eV"] and row["n_atoms"]:
        try:
            row["e_per_atom_eV"] = round(float(row["e_static_eV"]) / int(row["n_atoms"]), 6)
        except (TypeError, ValueError, ZeroDivisionError):
            pass

    row["fail_reason"] = "; ".join(fails)
    # `ready` is the only column the hull builder looks at: a static energy that
    # came after a relax that actually converged.
    row["ready"] = bool(row["e_static_eV"] != "" and row["relax_converged"] is True
                        and row["static_state"] == "done")
    return row


def cmd_index(a) -> None:
    root = store_root()
    folders = sorted(p for p in structures_dir().glob("mp-*") if p.is_dir())
    # Every scan is a handful of small NFS reads, so this is latency-bound, not
    # CPU-bound: threads turn a 10-minute serial walk into well under a minute.
    from concurrent.futures import ThreadPoolExecutor
    rows = []
    with ThreadPoolExecutor(max_workers=a.workers) as pool:
        for i, row in enumerate(pool.map(scan_one, folders), 1):
            rows.append(row)
            if i % 500 == 0:
                print(f"  scanned {i}/{len(folders)}", flush=True)
    rows.sort(key=lambda r: r["folder"])

    csv_path = root / "index.csv"
    with csv_path.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)
    (root / "index.json").write_text(json.dumps(rows, indent=1, default=str))

    ready = sum(1 for r in rows if r["ready"])
    print(f"{len(rows)} structures -> {csv_path}")
    print(f"  hull-ready       {ready}")
    for stage in STAGES:
        c = Counter(r[f"{stage}_state"] for r in rows)
        print(f"  {stage:<8} " + "  ".join(f"{k}={v}" for k, v in sorted(c.items())))
    c = Counter(r["mlip_state"] for r in rows)
    print("  mlip     " + "  ".join(f"{k}={v}" for k, v in sorted(c.items())))


def load_index() -> list[dict]:
    p = store_root() / "index.csv"
    if not p.is_file():
        sys.exit(f"no {p}. Run: refstore.py index")
    with p.open() as fh:
        return list(csv.DictReader(fh))


# --------------------------------------------------------------------------
# refresh -- rewrite the inputs of every unfinished stage, keeping progress
# --------------------------------------------------------------------------

def refresh_folder(folder: Path, *, ntasks: int | None = None,
                   apply: bool = False) -> dict:
    """Put one unfinished structure back in a runnable, correctly-parallel state.

    Three things happen, in this order, and the order is the whole point:

      1. the geometry the last attempt actually REACHED is preserved
         (dft_relax/CONTCAR), so a killed relax continues rather than
         restarting from the MP cell;
      2. the residue of that attempt is removed, because a half-written OUTCAR
         beside a live one is unreadable and a stale CHGCAR can poison the run
         it is meant to help;
      3. the inputs are rewritten WITH the rank count, which is what turns the
         KPAR/NCORE planner on.  Folders written before 2026-09-10 have no
         KPAR at all -- see docs/10-reference-set.md.

    The relax k-grid is re-derived from the restart cell.  That is safe: it is
    a reciprocal DENSITY, so the grid barely moves, and the energy that reaches
    the hull comes from the static, whose grid is re-derived from the relaxed
    cell either way.  The relax grid only affects the path.
    """
    rec = {"folder": folder.name, "action": "-", "kpar_before": None,
           "kpar_after": None, "cleaned": "-", "geometry": "-"}
    relax = folder / "dft_relax"
    inc = relax / "INCAR"
    if inc.is_file():
        rec["kpar_before"] = "KPAR" in inc.read_text()

    # Where to restart from, best first.  CONTCAR is the cell the last attempt
    # reached.  If there is none but a POSCAR is present, that POSCAR IS the
    # reached cell -- a previous refresh already carried it there and removed
    # the CONTCAR -- so it must be preferred over the seed chain.  Without this
    # branch a second refresh silently throws the first one's progress away and
    # restarts from the MLIP cell; measured on mp-1056831-O2, 2026-09-10.
    contcar = relax / "CONTCAR"
    poscar = relax / "POSCAR"
    if contcar.is_file() and contcar.stat().st_size > 0:
        restart_from, rec["geometry"] = contcar, "CONTCAR (continue)"
    elif poscar.is_file() and poscar.stat().st_size > 0:
        restart_from, rec["geometry"] = poscar, "POSCAR (continue)"
    else:
        restart_from, rec["geometry"] = None, "seed (restart)"
    resume = restart_from is not None

    if not apply:
        rec["action"] = "would refresh"
        return rec

    # 1. keep the reached geometry out of clean_stage's way
    keep = relax / "POSCAR.restart"
    if resume:
        shutil.copyfile(restart_from, keep)

    # 2. remove the previous attempt
    # clean_stage returns the REASON string it logged, not a count.
    rec["cleaned"] = clean_stage(relax, carry_contcar=False) or "-"
    clean_stage(folder / "dft_static", carry_contcar=False)

    # 3. rewrite the inputs with the planner on
    try:
        # `folder`, NOT `relax`: write_stage_inputs appends STAGE_DIR itself,
        # so handing it the stage directory writes dft_relax/dft_relax and
        # leaves the real INCAR untouched.  Caught by a two-folder test.
        write_stage_inputs(folder, "relax", ntasks=ntasks,
                           geometry=keep if resume else None)
    finally:
        keep.unlink(missing_ok=True)

    rec["kpar_after"] = "KPAR" in inc.read_text() if inc.is_file() else False
    rec["action"] = "refreshed"
    return rec


def cmd_refresh(a) -> None:
    root = store_root()
    rows = [r for r in load_index() if r["ready"] != "True"]
    if a.folder:
        rows = [r for r in rows if r["folder"] in set(a.folder)]
    if a.chemsys:
        want = set(a.chemsys.split("-"))
        rows = [r for r in rows
                if r["chemsys"] and set(r["chemsys"].split("-")) <= want]

    ignored = load_ignored()
    skipped_ignored = [r for r in todo if r["mp_id"] in ignored]
    if skipped_ignored:
        todo = [r for r in todo if r["mp_id"] not in ignored]
        print(f"skipping {len(skipped_ignored)} structure(s) listed in "
              f"ignored.json -- too far above the hull to matter, not failures")

    held = folders_in_flight(root)
    skipped = [r for r in rows if r["folder"] in held]
    rows = [r for r in rows if r["folder"] not in held]
    if skipped:
        print(f"skipping {len(skipped)} folder(s) held by a live task -- "
              f"refreshing one under a running VASP would corrupt it")
    if a.limit:
        rows = rows[: a.limit]

    n = job_ntasks(a.ntasks)
    print(f"{len(rows)} folder(s) to refresh, planning for {n} ranks")
    recs = []
    for r in rows:
        rec = refresh_folder(structures_dir() / r["folder"], ntasks=n, apply=a.apply)
        recs.append(rec)
        if a.verbose or len(rows) <= 20:
            print(f"  {rec['folder']:<26} {rec['geometry']:<20} "
                  f"KPAR {rec['kpar_before']} -> {rec['kpar_after']}  "
                  f"{str(rec['cleaned'])[:52]}")
    gained = sum(1 for r in recs if r["kpar_before"] is False and r["kpar_after"])
    cont = sum(1 for r in recs if r["geometry"].startswith("CONTCAR"))
    print(f"  continued from CONTCAR        {cont}")
    print(f"  restarted from the seed       {len(recs) - cont}")
    if a.apply:
        print(f"  gained KPAR (had none)        {gained}")
    else:
        print("\ndry run. add --apply to rewrite.")


# --------------------------------------------------------------------------
# status
# --------------------------------------------------------------------------

def cmd_status(a) -> None:
    rows = load_index()
    ignored = load_ignored()
    # store_root(), not a bare `root` -- that name is local to cmd_submit,
    # where this stale-index warning was written first.
    age = (time.time() - (store_root() / "index.csv").stat().st_mtime) / 60
    if age > 10:
        print(f"note: index.csv is {age:.0f} minutes old. Every folder is "
              f"re-read before anything is deleted, so this is safe -- but "
              f"`refstore.py index` first gives a truer task list.")
    if a.chemsys:
        want = set(a.chemsys.split("-"))
        rows = [r for r in rows
                if r["chemsys"] and set(r["chemsys"].split("-")) <= want]
        print(f"chemsys {a.chemsys}: {len(rows)} phases in the store "
              f"(including every sub-system)")
    ready = [r for r in rows if r["ready"] == "True"]
    todo = [r for r in rows if r["ready"] != "True"]
    # IGNORED is a third state, not a kind of failure.  Counting these as
    # outstanding work made the store look 67 structures further from done
    # than it is, and invited exactly the wasted effort this file prevents.
    skip = [r for r in todo if r["mp_id"] in ignored]
    todo = [r for r in todo if r["mp_id"] not in ignored]
    print(f"total            {len(rows)}")
    print(f"hull-ready       {len(ready)}")
    if skip:
        print(f"ignored          {len(skip)}   (too far above the hull to "
              f"matter -- see ignored.json; NOT failures)")
    print(f"outstanding      {len(todo)}")
    c = Counter(r["fail_reason"] or f"{r['relax_state']}/{r['static_state']}"
                for r in todo)
    for k, v in c.most_common(12):
        print(f"  {v:>5}  {k}")


# --------------------------------------------------------------------------
# inputs -- write VASP input files for one stage of one folder
# --------------------------------------------------------------------------

def sbatch_ntasks(script: str = "refstore_dft.sbatch") -> int | None:
    """The rank count the DFT job itself declares, read from its #SBATCH line.

    This is the authority, not the environment.  See job_ntasks().
    """
    f = Path(__file__).with_name(script)
    try:
        for line in f.read_text().splitlines():
            if line.startswith("#SBATCH") and "--ntasks=" in line:
                return int(line.split("--ntasks=")[1].split()[0])
    except (OSError, ValueError, IndexError):
        pass
    return None


def job_ntasks(explicit: int | None = None) -> int:
    """How many MPI ranks the VASP job will have.

    This is NOT cosmetic.  `resolve_inputs` only runs its parallel planner when
    it is told the rank count -- `if ntasks:` -- so leaving it None silently
    ships every INCAR with KPAR unset, i.e. KPAR=1, i.e. VASP walking the
    k-points one after another with no k-point parallelism at all.  Measured
    2026-09-10 on the iron-oxide tail of this store, that cost 4x to 8x on the
    ten slowest running jobs.  See docs/10-reference-set.md.

    $SLURM_NTASKS is trusted ONLY when this process is actually inside the DFT
    array task.  A login shell can be inside an allocation of its own: this
    cluster's Open OnDemand dashboard runs with SLURM_NTASKS=2, so a hand-run
    `inputs` or `refresh` from such a shell would otherwise plan a 32-rank job
    for 2 ranks and write a KPAR that does not divide the real rank count --
    which VASP rejects at startup.  Found the hard way, 2026-09-10.

    Order: an explicit --ntasks; else SLURM's value if we are in a ref-dft
    task; else what refstore_dft.sbatch itself asks for; else the machine
    profile default.
    """
    if explicit:
        return int(explicit)
    if os.environ.get("SLURM_JOB_NAME", "").startswith("ref-"):
        for var in ("SLURM_NTASKS", "SLURM_NPROCS"):
            val = os.environ.get(var)
            if val and val.isdigit() and int(val) > 0:
                return int(val)
    from_script = sbatch_ntasks()
    if from_script:
        return from_script
    try:
        _, _, machine = policy()
        return int(getattr(machine.defaults, "ntasks", 0)) or 32
    except Exception:
        return 32


def write_stage_inputs(folder: Path, stage: str, ntasks: int | None = None,
                       geometry: Path | None = None) -> Path:
    """Write INCAR/KPOINTS/POSCAR/POTCAR for `stage` into `folder`.

    The geometry comes from the best available source, in this order:
        static : dft_relax/CONTCAR   (the relaxed cell -- this is the carry)
        relax  : mlip/CONTCAR, else the MP structure in POSCAR.orig
    """
    from cspflow.dft.vasp.inputs import resolve_inputs, write_inputs

    dft, recipe, machine = policy()
    st = {s.name: s for s in recipe.stages}[stage]
    out = folder / STAGE_DIR[stage]

    if geometry is not None:
        # An explicit restart geometry.  `refresh` uses this to rewrite an
        # INCAR from the cell a killed relax had already reached, instead of
        # throwing that progress away and starting from the seed again.
        src = Path(geometry)
        if not src.is_file() or not src.stat().st_size:
            raise SystemExit(f"{folder.name}: --geometry {src} is missing or empty")
    elif stage == "static":
        src = folder / "dft_relax" / "CONTCAR"
        if not src.is_file() or src.stat().st_size == 0:
            raise SystemExit(f"{folder.name}: no relaxed CONTCAR to carry into static")
    else:
        # `dft_relax/POSCAR` is the ORIGINAL input geometry -- VASP never
        # overwrites it (it writes CONTCAR instead) -- so it is the right seed
        # for a folder migrated from the old layout, which has no POSCAR.orig.
        for cand in ("mlip/CONTCAR", "POSCAR.orig", "dft_relax/POSCAR"):
            src = folder / cand
            if src.is_file() and src.stat().st_size:
                break
        else:
            raise SystemExit(f"{folder.name}: no starting geometry")

    atoms = read_atoms(src)
    # ntasks is what turns the KPAR/NCORE planner on -- see job_ntasks().
    resolved = resolve_inputs(atoms, st, dft, machine, ntasks=job_ntasks(ntasks))
    out.mkdir(parents=True, exist_ok=True)
    write_inputs(resolved, resolved.atoms if resolved.atoms is not None else atoms, out)
    return out


def cmd_inputs(a) -> None:
    folder = Path(a.dir)
    if not folder.is_absolute():
        folder = structures_dir() / folder
    out = write_stage_inputs(folder, a.stage, ntasks=getattr(a, "ntasks", None),
                             geometry=Path(a.geometry) if getattr(a, "geometry", None) else None)
    tags = {}
    for line in (out / "INCAR").read_text().splitlines():
        k, _, v = line.partition("=")
        if v:
            tags[k.strip()] = v.split("#")[0].strip()
    print(f"{out}  KPAR={tags.get('KPAR', 'unset')} "
          f"NCORE={tags.get('NCORE', 'unset')} ntasks={job_ntasks(getattr(a, 'ntasks', None))}")


# --------------------------------------------------------------------------
# add -- fetch MP for a chemical system and create what is missing
# --------------------------------------------------------------------------

def cmd_add(a) -> None:
    from cspflow.reference.mp import fetch_chemsys, fetch_structures

    root = store_root()
    cache = root / "mp-cache"
    cache.mkdir(parents=True, exist_ok=True)
    have = {p.name.split("-")[0] + "-" + p.name.split("-")[1]
            for p in structures_dir().glob("mp-*") if p.is_dir()}

    created, skipped_have, skipped_far = 0, 0, 0
    for chemsys in a.chemsys:
        res = fetch_chemsys(chemsys, cache=cache)
        structs = fetch_structures(chemsys, cache=cache)
        print(f"{chemsys}: {len(res.entries)} MP entries "
              f"(includes every sub-system)")
        for e in res.entries:
            if e.mp_id in have:
                skipped_have += 1
                continue
            # `e_above_hull_mp`, not `e_above_hull`.  The attribute was
            # misnamed here, so `above` was ALWAYS None: --cut never fired and
            # every info.json recorded a null distance.  Found 2026-09-11.
            above = getattr(e, "e_above_hull_mp", None)
            if a.cut and above is not None and above > a.cut:
                skipped_far += 1
                continue
            s = structs.get(e.mp_id)
            if s is None:
                continue
            folder = structures_dir() / slug(e.mp_id, s.composition.reduced_formula)
            created += 1
            if not a.apply:
                continue
            folder.mkdir(parents=True, exist_ok=True)
            from pymatgen.io.vasp.inputs import Poscar
            Poscar(s).write_file(str(folder / "POSCAR.orig"))
            (folder / "info.json").write_text(json.dumps({
                "mp_id": e.mp_id,
                "formula": s.composition.reduced_formula,
                "chemsys": "-".join(sorted({str(x) for x in s.composition.elements})),
                "n_atoms": len(s),
                "source": "materials-project",
                "e_above_hull_mp": above,
                "requested_for": chemsys,
            }, indent=2))

    print(f"\nalready in the store   {skipped_have}")
    print(f"above the {a.cut} eV/atom cut  {skipped_far}")
    print(f"to create              {created}")
    if not a.apply:
        print("\ndry run. add --apply to create the folders.")



# Files VASP writes.  Everything else in a stage directory is an input we keep.
VASP_OUTPUTS = ("OUTCAR", "OSZICAR", "vasprun.xml", "CONTCAR", "CHG", "CHGCAR",
                "WAVECAR", "EIGENVAL", "DOSCAR", "PROCAR", "PCDAT", "XDATCAR",
                "REPORT", "IBZKPT", "vasp.out", "VASP_DONE", "POSCAR.prev",
                "vaspout.h5", "ML_LOGFILE")

FAILURE_HINT = re.compile(
    r"(ZBRENT[^|\n]{0,40}|VERY BAD NEWS[^|\n]{0,60}|illegal instruction"
    r"|reached required accuracy)")


def clean_stage(stage_dir: Path, *, carry_contcar: bool) -> str:
    """Delete a dead attempt's output, keeping one line saying what it was.

    Two reasons this is not optional.  A rerun that leaves the old files in
    place gives you a directory holding half of a dead run and half of a live
    one the moment the new attempt crashes early -- and `refcheck.py`, reading
    the stale OUTCAR, keeps reporting a failure that was already fixed.  A
    leftover CHGCAR or WAVECAR from a crashed run can also poison the restart
    it is supposed to accelerate.

    `carry_contcar` is for the relax: the geometry the dead attempt reached is
    the one thing worth keeping, so it becomes the new POSCAR *before* the
    delete, not after.
    """
    if not stage_dir.is_dir():
        return ""

    reason = ""
    for name in ("OUTCAR", "vasp.out"):
        f = stage_dir / name
        if f.is_file() and f.stat().st_size:
            m = FAILURE_HINT.search(tail_text(f))
            if m:
                reason = m.group(1).strip()
                break

    contcar = stage_dir / "CONTCAR"
    if carry_contcar and contcar.is_file() and contcar.stat().st_size:
        (stage_dir / "POSCAR").write_bytes(contcar.read_bytes())
        reason = (reason + "; " if reason else "") + "geometry carried to POSCAR"

    removed = 0
    for name in VASP_OUTPUTS:
        f = stage_dir / name
        if f.is_file():
            f.unlink()
            removed += 1
    if removed:
        with (stage_dir / "RETRY.log").open("a") as fh:
            fh.write(f"{time.strftime('%Y-%m-%dT%H:%M:%S')}  cleaned {removed} "
                     f"file(s) from the previous attempt"
                     f"{' -- ' + reason if reason else ''}\n")
    return reason


# --------------------------------------------------------------------------
# submit
# --------------------------------------------------------------------------

def cmd_submit(a) -> None:
    root = store_root()
    jobs = root / "jobs"
    jobs.mkdir(parents=True, exist_ok=True)
    rows = load_index()

    if a.what == "mlip":
        todo = [r for r in rows if r["mlip_state"] in ("todo", "partial")]
        script = Path(__file__).with_name("refstore_mlip.sbatch")
    else:
        # Deliberately NOT gated on the MLIP.  The MLIP only supplies a better
        # starting geometry; MP's own relaxed cell is a valid seed on its own,
        # and gating on it would park 2,869 structures behind a GPU queue.
        #
        # The test is `ready`, NOT `static_state != done`.  A structure whose
        # relax was killed mid-run but whose static then ran anyway looks
        # finished and is not: that static energy sits on an unrelaxed cell.
        # One such row (mp-1181327-Fe3B) was already in the store.
        todo = [r for r in rows if r["ready"] != "True"]
        script = Path(__file__).with_name("refstore_dft.sbatch")

    # Structures the store has decided not to wait for.  IGNORED, not failed:
    # they compute fine, they just sit too far above the hull to change it.
    # Listed in <store>/ignored.json so the decision is reviewable -- delete an
    # entry there and the structure comes straight back into the queue.
    ignored = load_ignored()
    if ignored and a.what == "dft":
        before = len(todo)
        todo = [r for r in todo if r["mp_id"] not in ignored]
        if before != len(todo):
            print(f"skipping {before - len(todo)} structure(s) in ignored.json "
                  f"-- too far above the hull to matter (not failures)")

    # Never hand a folder to a second job while the first still holds it: two
    # VASP processes writing one directory is corruption, not a race.
    in_flight = folders_in_flight(root)
    if in_flight:
        before = len(todo)
        todo = [r for r in todo if r["folder"] not in in_flight]
        if before != len(todo):
            print(f"skipping {before - len(todo)} structure(s) already handed to "
                  f"a job that is still queued or running")

    if a.chemsys:
        want = set(a.chemsys.split("-"))
        todo = [r for r in todo if r["chemsys"]
                and set(r["chemsys"].split("-")) <= want]
        print(f"restricted to {a.chemsys} (and its sub-systems)")
    if a.limit:
        todo = todo[: a.limit]
    if not todo:
        print(f"nothing to do for {a.what}")
        return

    # Stamped, because a running array reads its task file line by line for as
    # long as it lives.  A second submission reusing the name would rewrite the
    # list under a job already using it, and every task not yet started would
    # run the wrong structure.
    tag = (a.chemsys or "all").replace("-", "")
    tasks = jobs / f"{a.what}-{tag}-{time.strftime('%m%d-%H%M')}.tasks"
    if a.apply:
        # Only on --apply: a dry run that rewrote this would silently change the
        # task list a running array is reading line by line.
        tasks.write_text("".join(f"{structures_dir() / r['folder']}\n"
                                 for r in todo))
    print(f"{len(todo)} task(s) -> {tasks}"
          f"{'' if a.apply else '  (not written -- dry run)'}")

    if a.what == "dft" and a.apply:
        # Wipe every stage that is about to be redone.  This is also what makes
        # `refcheck.py` honest: without it, a structure queued for a rerun keeps
        # reporting its OLD failure until the new attempt overwrites the file.
        #
        # RE-READ EACH FOLDER FIRST.  index.csv is a snapshot, and jobs finish
        # while you are looking at it.  Cleaning straight from the index deleted
        # 168 completed statics and 76 converged relaxes here on 2026-09-09 --
        # work that a running array had produced in the 38 minutes between the
        # index being built and the submit being typed.  Nothing was lost for
        # good, because everything wiped was resubmitted, but the CPU was.
        cleaned = skipped = 0
        keep = []
        for r in todo:
            folder = structures_dir() / r["folder"]
            fresh = scan_one(folder)
            if fresh["ready"] is True:
                skipped += 1
                continue                       # finished since the index was built
            keep.append(r)
            if fresh["relax_converged"] is not True:
                clean_stage(folder / "dft_relax", carry_contcar=True)
                cleaned += 1
            # A relax that has to be redone invalidates its own static: that
            # energy sits on a cell that is about to change.  But if the relax
            # stands, a finished static must not be touched.
            if fresh["relax_converged"] is not True or fresh["static_state"] != "done":
                clean_stage(folder / "dft_static", carry_contcar=False)
                cleaned += 1
        if skipped:
            print(f"skipped {skipped} structure(s) that finished after the index "
                  f"was built -- rerun `index` to see them")
            todo = keep
            tasks.write_text("".join(f"{structures_dir() / r['folder']}\n"
                                     for r in todo))
            if not todo:
                print("nothing left to submit")
                return
        print(f"cleaned {cleaned} stage director(ies) of previous output")

    refstore = Path(__file__).resolve()
    # DFT is one array task per structure (each is hours of MPI).  MLIP is
    # chunked: loading the MatterSim model costs ~30 s, so a task that relaxed a
    # single small cell would spend most of its life in the import.
    if a.what == "mlip":
        n_tasks = -(-len(todo) // a.chunk)
    else:
        n_tasks = len(todo)          # after any post-clean shrink above
    cmd = ["sbatch",
           f"--array=0-{n_tasks - 1}%{a.throttle}",
           f"--chdir={root}",
           f"--output={jobs}/{a.what}-{tag}-%A_%a.out",
           f"--export=ALL,REFSTORE_TASKS={tasks},CSPFLOW_STORE={root},"
           f"REFSTORE={refstore},REFSTORE_CHUNK={a.chunk}",
           str(script)]
    print(" ".join(cmd))
    if not a.apply:
        print("\ndry run. add --apply to submit.")
        return
    done = subprocess.run(cmd, check=True, capture_output=True, text=True)
    print(done.stdout.strip())
    job_id = "".join(c for c in done.stdout if c.isdigit())
    if job_id:
        tasks.with_suffix(".tasks.jobid").write_text(job_id)



def folders_in_flight(root: Path) -> set[str]:
    """Structure folders already handed to a job that is still queued/running.

    Submitting one twice is not a nuisance, it is corruption: two VASP processes
    writing one directory.  Each submission records its job id beside its task
    file, so this only has to ask the scheduler which of those are still alive.
    """
    live: set[str] = set()
    for stamp in sorted((root / "jobs").glob("*.tasks.jobid")):
        job_id = stamp.read_text().strip()
        tasks = stamp.with_suffix("")                       # <name>.tasks
        if not job_id or not tasks.is_file():
            continue
        try:
            out = subprocess.run(
                ["squeue", "-h", "-j", job_id, "-t", "PD,R", "-o", "%i"],
                capture_output=True, text=True, timeout=30)
        except Exception:                                        # noqa: BLE001
            continue

        # Only tasks still PENDING or RUNNING hold their folder.  An array index
        # that already finished -- successfully or not -- will never run again,
        # so treating the whole task file as live would permanently block the
        # very structures that need a second attempt.
        indices: set[int] = set()
        for line in out.stdout.split():
            _, _, part = line.partition("_")
            part = part.strip("[]")
            for chunk in part.split(","):
                chunk = chunk.split("%")[0]
                if "-" in chunk:
                    lo, _, hi = chunk.partition("-")
                    if lo.isdigit() and hi.isdigit():
                        indices.update(range(int(lo), int(hi) + 1))
                elif chunk.isdigit():
                    indices.add(int(chunk))

        lines = [ln for ln in tasks.read_text().splitlines() if ln.strip()]
        live.update(Path(lines[i]).name for i in indices if i < len(lines))
    return live


# --------------------------------------------------------------------------
# hull
# --------------------------------------------------------------------------

def load_ignored() -> dict[str, dict]:
    """mp_id -> record, from <store>/ignored.json.

    IGNORED is not FAILED.  These structures compute fine; they just sit too
    far above the convex hull to be able to change it, so the store does not
    wait for them.  Kept as a file rather than a rule so the decision is
    reviewable and reversible: delete an entry and it comes back.

    Distinct from excluded.json, which holds structures that CANNOT be
    computed as given (vacuum clusters, 0.80 A contacts).  Those are failures.
    """
    f = store_root() / "ignored.json"
    try:
        return json.loads(f.read_text()).get("ignored", {})
    except (OSError, ValueError):
        return {}


def mp_hull_distance() -> dict[str, float]:
    """mp_id -> MP's own e_above_hull, read from the store's fetch cache.

    Used only to decide whether a MISSING structure can matter. A phase far
    above the hull cannot be on it, so waiting for it is waiting for nothing.
    The number is MP's, computed at MP's settings -- but e_above_hull is a
    distance WITHIN a chemical system, so the systematic ours-minus-MP offset
    (measured 0.15-0.21 eV/atom on this store) largely cancels. It is a
    triage number, never an energy that reaches a hull.
    """
    out: dict[str, float] = {}
    for f in (store_root() / "mp-cache").glob("*__GGA_GGApU.json"):
        try:
            data = json.loads(f.read_text())
        except (OSError, ValueError):
            continue
        for e in data.get("entries", []):
            mid, eah = e.get("mp_id"), e.get("e_above_hull_mp")
            if mid is not None and eah is not None:
                out[mid] = min(out.get(mid, float("inf")), float(eah))
    return out


def cmd_hull(a) -> None:
    """Build a hull from the store FOLDER, on one of its three energy scales.

    No export step and no recipe_id: the store is the source of truth and the
    entries are read out of it. See cspflow/reference/refstore.py.
    """
    from cspflow.reference.hull import build_hull
    from cspflow.reference.refstore import (ENERGY_SOURCES, StoreError,
                                            coverage, entries_for, stale_minutes)

    age = stale_minutes()
    if age > 10:
        print(f"note: index.csv is {age:.0f} minutes old -- `refstore.py index` "
              f"first if a batch has finished since.")

    sources = list(ENERGY_SOURCES) if a.compare else [a.energy]
    for src in sources:
        cov = coverage(a.chemsys, src)
        far = mp_hull_distance()
        blocking = [m for m in cov.missing if far.get(m, float("inf")) <= a.ignore_above]
        waivable = [m for m in cov.missing if m not in blocking]

        head = f"{a.chemsys} [{src}]"
        print(f"\n{head}: {len(cov.have)} usable, {len(cov.missing)} without an energy")
        if cov.ignored:
            print(f"  {len(cov.ignored)} in ignored.json (too far above the hull to matter)")
        if waivable:
            # unfinished, but MP puts them far enough above the hull that they
            # cannot be vertices -- refusing over these blocks a campaign for
            # nothing. Named anyway: a phase silently dropped is how a hull
            # quietly becomes wrong.
            print(f"  {len(waivable)} unfinished but > {a.ignore_above} eV/atom above "
                  f"MP's hull -- ignored:")
            for m in waivable[:8]:
                print(f"    {m:<18} MP e_above_hull {far.get(m, float('nan')):.3f}")
        if blocking:
            print(f"  {len(blocking)} unfinished and CLOSE ENOUGH to matter "
                  f"(<= {a.ignore_above} eV/atom):")
            for m in blocking:
                d = far.get(m, float("inf"))
                tag = "ON THE HULL" if d <= 0.001 else f"e_above_hull {d:.3f}"
                print(f"    {m:<18} {tag}")
            print("\nA hull built without these is not the hull. Finish them first:")
            print(f"  python {Path(__file__).name} submit dft --chemsys {a.chemsys} --apply")
            continue
        try:
            entries = entries_for(a.chemsys, src, allow_partial=True)
        except StoreError as exc:
            print(f"  {exc}")
            continue
        print(build_hull(entries).render())


# --------------------------------------------------------------------------
# mlip -- MatterSim relax, straight into <folder>/mlip/
# --------------------------------------------------------------------------

# Largest lattice parameter accepted for a STORE structure, in Angstrom.  The
# store is MP-derived; the longest axis it holds after Niggli reduction is
# ~65 A (mp-684606, Cu27Se20).  120 leaves headroom without admitting a cell
# whose axis is longer than any real crystal in the set.
STORE_MAX_LATTICE_A = 120.0


def relax_one_mlip(folder: Path, engine) -> dict:
    """Relax one structure with the MLIP and write `mlip/` beside the DFT dirs.

    The relaxed cell is the useful product: it is a far better starting point
    for the DFT relax than MP's own geometry, and it used to be thrown away.
    """
    from ase.io import write as ase_write

    for cand in ("POSCAR.orig", "dft_relax/POSCAR"):
        seed = folder / cand
        if seed.is_file() and seed.stat().st_size:
            break
    else:
        return {"folder": folder.name, "ok": False, "error": "no seed geometry"}

    atoms = read_atoms(seed)
    res = engine.relax(atoms)
    out = folder / "mlip"
    out.mkdir(parents=True, exist_ok=True)
    rec = {
        "mp_id": "-".join(folder.name.split("-")[:2]),
        "formula": atoms.get_chemical_formula(),
        "converged": bool(res.converged),
        "e_mlip_relaxed": res.energy,
        "e_per_atom": res.e_per_atom,
        "mlip_fmax": res.fmax,
        "mlip_steps": res.n_steps,
        "model": getattr(engine, "model", ""),
        "volume_initial": float(atoms.get_volume()),
    }
    if res.atoms is not None:
        ase_write(str(out / "CONTCAR"), res.atoms, format="vasp", direct=True)
        ase_write(str(out / "relaxed.cif"), res.atoms)
        rec["volume_final"] = float(res.atoms.get_volume())
    (out / "mlip.json").write_text(json.dumps(rec, indent=2, sort_keys=True))
    return {"folder": folder.name, "ok": res.energy is not None, **rec}


def cmd_mlip(a) -> None:
    from cspflow.mlip import MatterSimEngine, apply_ase_compat_shim

    apply_ase_compat_shim()
    if a.tasks:
        folders = [Path(line) for line in
                   Path(a.tasks).read_text().split() if line.strip()]
    else:
        folders = [structures_dir() / d if not Path(d).is_absolute() else Path(d)
                   for d in a.dirs]
    if a.start or a.count:
        folders = folders[a.start: a.start + a.count if a.count else None]

    # The store's structures come from Materials Project, so a long axis is a
    # real long-period polytype (Cu27Se20 is c = 65 A) rather than the generated
    # nonsense the 50 A default guards against.  Raising the cap here does not
    # touch campaign screening, which keeps the default.
    engine = MatterSimEngine(max_lattice=STORE_MAX_LATTICE_A)
    ok = bad = 0
    for i, f in enumerate(folders, 1):
        try:
            r = relax_one_mlip(f, engine)
            ok += bool(r.get("ok"))
            bad += not r.get("ok")
            print(f"[{i}/{len(folders)}] {f.name:<28} "
                  f"E={r.get('e_mlip_relaxed')} fmax={r.get('mlip_fmax')}", flush=True)
        except Exception as exc:                                    # noqa: BLE001
            bad += 1
            print(f"[{i}/{len(folders)}] {f.name:<28} FAILED: {exc}", flush=True)
    print(f"done: {ok} ok, {bad} failed")


# --------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1],
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    m = sub.add_parser("migrate", help="fold old layouts into structures/")
    m.add_argument("--apply", action="store_true")
    m.set_defaults(fn=cmd_migrate)

    ad = sub.add_parser("add", help="fetch MP and add missing phases")
    ad.add_argument("chemsys", nargs="+")
    ad.add_argument("--cut", type=float, default=DEFAULT_CUT,
                    help=f"skip phases this far above MP's hull (default {DEFAULT_CUT})")
    ad.add_argument("--apply", action="store_true")
    ad.set_defaults(fn=cmd_add)

    i = sub.add_parser("inputs", help="write VASP inputs for one stage")
    i.add_argument("dir")
    i.add_argument("--stage", choices=STAGES, required=True)
    i.add_argument("--geometry", help="restart from this POSCAR/CONTCAR instead "
                                      "of the usual seed chain")
    i.add_argument("--ntasks", type=int,
                   help="MPI ranks the job will use; sets KPAR/NCORE. "
                        "Defaults to $SLURM_NTASKS inside a job.")
    i.set_defaults(fn=cmd_inputs)

    rf = sub.add_parser("refresh",
                        help="rewrite unfinished stages' inputs, keeping progress")
    rf.add_argument("folder", nargs="*", help="specific folder name(s)")
    rf.add_argument("--chemsys")
    rf.add_argument("--limit", type=int)
    rf.add_argument("--ntasks", type=int)
    rf.add_argument("--apply", action="store_true")
    rf.add_argument("-v", "--verbose", action="store_true")
    rf.set_defaults(fn=cmd_refresh)

    ix = sub.add_parser("index", help="rescan the tree -> index.csv")
    ix.add_argument("--workers", type=int, default=32)
    ix.set_defaults(fn=cmd_index)

    st = sub.add_parser("status", help="human summary")
    st.add_argument("chemsys", nargs="?")
    st.set_defaults(fn=cmd_status)

    sb = sub.add_parser("submit", help="write a task list and sbatch it")
    sb.add_argument("what", choices=["mlip", "dft"])
    sb.add_argument("--limit", type=int, default=0)
    sb.add_argument("--chemsys", help="only structures inside this system")
    sb.add_argument("--throttle", type=int, default=40)
    sb.add_argument("--chunk", type=int, default=50,
                    help="structures per array task (mlip only)")
    sb.add_argument("--apply", action="store_true")
    sb.set_defaults(fn=cmd_submit)

    ml = sub.add_parser("mlip", help="MatterSim relax into <folder>/mlip/")
    ml.add_argument("dirs", nargs="*")
    ml.add_argument("--tasks", help="file with one folder path per line")
    ml.add_argument("--start", type=int, default=0)
    ml.add_argument("--count", type=int, default=0)
    ml.set_defaults(fn=cmd_mlip)

    h = sub.add_parser("hull", help="build the hull from index.csv")
    h.add_argument("chemsys")
    h.add_argument("--energy", choices=("dft","mlip","mp"), default="dft",
                   help="which of the store's three energies to build on "
                        "(default dft). They are never mixed.")
    h.add_argument("--compare", action="store_true",
                   help="build all three hulls side by side")
    h.add_argument("--ignore-above", type=float, default=0.10, metavar="eV/atom",
                   help="treat an unfinished phase further than this above MP's "
                        "own hull as unable to matter (default 0.10). RAISE it "
                        "to be stricter -- `--ignore-above 99` refuses on any "
                        "unfinished phase at all; 0 ignores everything except "
                        "phases exactly on MP's hull.")
    h.set_defaults(fn=cmd_hull)

    a = p.parse_args()
    a.fn(a)


if __name__ == "__main__":
    main()
